--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/XPocketMC/CustomWings
build-by-default: true
branches:
- stable
projects:
  CustomWings:
  libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
...
