name: CustomWings
api: 5.0.0
version: 1.0.0
main: CustomWings\Main
author: NurAzliYT
commands:
  customwings:
    description: "CustomWings"
    usage: /customwings
    permission: customwings.use
    aliases: [cw, wings]
permissions:
  customwings.use:
    default: true
